sqitch add 1.init_db -n "create domain, table and index"
sqitch add 2.add_constraint -n "Add constraint ON DELETE CASCADE on table user_has_family"
sqitch add 3.move_table_role -n "Move fkey role_id on table user_has_family"
sqitch add 4.create_function -n "Create function SQL for family_infos and user_infos"
sqitch add 5.add_primary_key -n "Add primary key on table user_has_family"